import React, { useEffect } from 'react';
import Head from "next/head";
import { useRouter } from "next/router";
import { Skeleton } from "@mantine/core";
import OtherInfo from "../../components/profile/OtherInfo";
import UserInfo from "../../components/profile/UserInfo";
import ProfileNavBar from "../../components/global/ProfileNavBar";
import UserBlogs from "../../components/profile/UserBlogs";
import {useQueryClient} from "react-query";
import {useAppSelector} from "../../hooks/redux-hooks";

const Profile = () => {

    const router = useRouter();
    const queryClient = useQueryClient();
    const num = queryClient.isFetching(['refreshToken']);

    const { auth, theme, socket, userLocation } = useAppSelector(state => state);
    const now = router.query.slug ? userLocation['user'][router.query.slug as string]?.['now'] : 'home'

    useEffect(() => {
        if(!socket || !router.query.slug) return;
        socket.emit('joinRoom', `profile_${router.query.slug}`);
        return () => {
            socket.emit('leaveRoom',`profile_${router.query.slug}`);
        }
    }, [socket, router.query.slug])

    if(!router.query.slug) return;

    return (
        <>
            <Head>
                <title>个人主页</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='row my-6'>
                <div className="col-md-5 mb-3">
                    {
                        num === 1 ? <Skeleton height={600} width={'100%'} className={`${theme && 'skeleton-night'}`}/> :  auth.user?._id === router.query.slug
                            ? <UserInfo/> : <OtherInfo id={router.query.slug as string}/>
                    }
                </div>
                <div className="col-md-7">
                    <ProfileNavBar slug={router.query.slug as string}/>
                    <UserBlogs name={now}/>
                </div>
            </div>
        </>
    );
};

export default Profile;
