import React, { useEffect } from 'react';
import Link from 'next/link';
import Head from "next/head";
import { useRouter } from "next/router";
import LoginPass from "../components/auth/LoginPass";
import {useAppDispatch, useAppSelector} from "../hooks/redux-hooks";
// import {setAlert} from "../features/alert";
import useTheme from "../hooks/util-hooks/useTheme";
import dynamic from "next/dynamic";

const SocialLogin = dynamic(() => import('../components/auth/SocialLogin'), { ssr: false})

const Login = () => {
    // const navigate = useNavigate();
    // const { key, search } = useLocation();
    const dispatch = useAppDispatch();
    const { auth } = useAppSelector(state => state);
    const { isSSGRTheme } = useTheme();
    const router = useRouter();

    // useEffect(() => {
    //     if(key === 'default' && (auth.access_token)) {
    //         dispatch(setAlert({ success: '已登入该系统，跳回主页' }))
    //     }
    // }, [key, dispatch, auth.access_token]);

    useEffect(() => {
        if(auth.access_token){
            // let url = search.replace('?', '/');
            // if(url === '') url = '/';
            router.push('/');
        }
    }, [auth.access_token , router]);

    return (
        <>
            <Head>
                <title>登录</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={`auth_page ${isSSGRTheme && 'auth-page-night'}`}>
                <div className="auth_box">
                    <h3 className='text-center mb-4'>
                        登录
                    </h3>
                    <SocialLogin/>
                    <LoginPass/>
                    <small className='row my-2 text-primary' style={{cursor: 'pointer'}}>
                    <span className='col-6'>
                        <Link href='/forgot_password' className='col-6'>
                           忘记密码?
                        </Link>
                    </span>
                    </small>
                    <p>
                        {`还没有账号？`}
                        <Link href={`/register`} style={{ color:'crimson' }}>
                            立即注册
                        </Link>
                    </p>
                </div>
            </div>
        </>
    );
};

export default Login;
