import React from 'react';
import Link from 'next/link';
import Head from 'next/head';
import {NextPage} from "next";
import RegisterForm from "../components/auth/RegisterForm";
import useCheckIfLoggedIn from "../hooks/util-hooks/useCheckIfLoggedIn";
import useTheme from "../hooks/util-hooks/useTheme";
// import {useAppSelector} from "../hooks/redux-hooks";
// import {useRouter} from "next/router";

const Register: NextPage = () => {

    // const router =  useRouter();
    // const { theme } = useAppSelector(state => state);
    const { isLogin } = useCheckIfLoggedIn()
    const { isSSGRTheme } = useTheme();

    return (
        <>
            <Head>
                <title>注册</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={`auth_page ${isSSGRTheme && 'auth-page-night'}`}>
                <div className="auth_box">
                    <h3 className='text-center mb-4'>
                        注册
                    </h3>
                    <RegisterForm isLogin={isLogin}/>
                    <p className="mt-2">
                        {`已经有账号了？`}
                        <Link href={`/login`} style={{ color:'crimson' }} passHref>
                            <a>立即登录</a>
                        </Link>
                    </p>
                </div>
            </div>
        </>
    );
};

export default Register;
